**Задание 1**
Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:
- если источник traffic_source равен yandex или google, то в source_type ставится organic
- для источников paid и email из России - ставим ad
- для источников paid и email не из России - ставим other
- все остальные варианты берем из traffic_source без изменений

In [1]:
import pandas as pd

In [10]:
log = pd.read_csv('visit_log.csv',sep=';')
log

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex
...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email

In [16]:
def source_t(source,region):
    if source in  ['yandex','google']:
        source_type='organic'
    elif region=='Russia' and source in ['paid','email']:
        source_type='ad'
    elif region!='Russia' and source in ['paid','email']:
        source_type='other'
    else:
        source_type=source
    return source_type

In [21]:
log['source_type']=log.apply(lambda x: source_t(x['traffic_source'], x['region']), axis=1)
log

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,other
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,ad
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,organic
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,ad

In [34]:
log.groupby(['source_type','region','traffic_source']).count()

                                      timestamp  visit_id   url  user_id
source_type region    traffic_source
ad          Russia    email                2209      2209  2209     2209
                      paid                 1581      1581  1581     1581
direct      Australia direct                222       222   222      222
            Belarus   direct                998       998   998      998
            China     direct                397       397   397      397
            India     direct                134       134   134      134
            Russia    direct               4052      4052  4052     4052
            Ukraine   direct               1210      1210  1210     1210
organic     Australia google                 91        91    91       91
                      yandex                 88        88    88       88
            Belarus   google                376       376   376      376
                      yandex                446       446   446      446
            China     google                151       151   151      151
                      yandex                171       171   171      171
            India     google                 55        55    55       55
                      yandex                 59        59    59       59
            Russia    google               1435      1435  1435     1435
                      yandex               1636      1636  1636     1636
            Ukraine   google                399       399   399      399
                      yandex                500       500   500      500
other       Australia email                 115       115   115      115
                      paid                   74        74    74       74
            Belarus   email                 569       569   569      569
                      paid                  368       368   368      368
            China     email                 252       252   252      252
                      paid                  138       138   138      138
            India     email                  82        82    82       82
                      paid                   39        39    39       39
            Ukraine   email                 648       648   648      648
                      paid                  443       443   443      443

**Задание 2**
В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:
1. Прочитайте содержимое файла с датафрейм
2. Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [28]:
URLs = pd.read_csv('URLs.txt')
URLs

                                                  url
0                                             /world/
1                                            /latest/
2                                       /?updated=top
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[93 rows x 1 columns]

In [33]:
import re

URLs[URLs['url'].str.contains('(\S)+/+(\d{8})+-',na=False)]

C:\Users\Admin\anaconda3\lib\site-packages\pandas\core\strings.py:1952: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

**Задание 3**
Сформулировано в конце кода занятия.
В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [32]:
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})
data

                 keyword   shows
0    курс гривны к рублю  125076
1        доллары в рубли  114173
2  100 долларов в рублях   97534
3             курс рубля   53546

In [36]:
import pymystem3

In [40]:
from pymystem3 import Mystem

In [53]:
m=Mystem()

keyword = str(data['keyword'].tolist()).strip('[]')

lemmas=m.lemmatize(keyword)

In [54]:
lemmas

["'",
 'курс',
 ' ',
 'гривна',
 ' ',
 'к',
 ' ',
 'рубль',
 "', '",
 'доллар',
 ' ',
 'в',
 ' ',
 'рубль',
 "', '",
 '100',
 ' ',
 'доллар',
 ' ',
 'в',
 ' ',
 'рубль',
 "', '",
 'курс',
 ' ',
 'рубль',
 "'\n"]

In [55]:
' '.join(lemmas)

"' курс   гривна   к   рубль ', ' доллар   в   рубль ', ' 100   доллар   в   рубль ', ' курс   рубль '\n"